###
POST http://localhost:3000/api/users/add_activities HTTP/1.1
content-type: application/json

{
    "jwt": "edienicndneincdicn",
    "sessionstart":"2019-06-12 17:11:51.632+00",
    "online":"false",
    "userId":"875"
}